name: receare
description: flutter test sns application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.2+1
  firebase_auth: ^0.18.3+1
  cloud_firestore: ^0.14.3+1
  google_sign_in: ^4.5.6

  http: ^0.12.2
  fluttertoast: ^7.1.4
  firebase_storage: ^4.0.1
  share: ^0.6.4+3
  flutter_email_sender: ^3.0.1
  analyzer: 0.39.17
  sqflite: ^1.3.1+1
  autocomplete_textfield: ^1.7.3
  flutter_typeahead: ^1.8.8
  path: ^1.7.0
  path_provider: ^1.6.14
  freezed_annotation:
  flutter_state_notifier:
  state_notifier:
  provider: ^4.1.0-dev+2
  uuid: ^2.0.4
  image_picker: ^0.6.7+12
  flutter_native_image: ^0.0.5+2
  flutter_sticky_header: ^0.5.0
  image: ^2.1.17
  file: ^5.2.1
  flutter_datetime_picker: ^1.4.0
  intl: ^0.16.1
  image_crop: ^0.3.4
  flutter_slidable: ^0.5.7
  rxdart: ^0.24.1
  multi_image_picker: ^4.7.14
  photo_view: any

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  freezed:

flutter:

  uses-material-design: true

